### ISSUE TITLE
fileformat.txt docs omit the `perRegionCoords` byte

### ISSUE THREAD

**Issue by fmoo** [johnnovak/gridmonger#10]
On the current main branch, the `perRegionCoords` byte is omitted.  It should be described [somewhere around here](https://github.com/johnnovak/gridmonger/blob/aeec8100009c23796119fa7516d7aed04998236b/extras/docs/fileformat.txt#L140-L142), in the "header" area of the chunk: 

I wasn't sure what the field means, so I'm not super comfortable putting up a PR for it.

**Comment by johnnovak** [comment]
Thanks for catching it. I might forget to update `fileformat.txt` from time to time, but I always update the documentation:

From: https://gridmonger.johnnovak.net/manual/regions.html

> You will then need to specify the region dimensions (**Region columns** and **Region rows**), and whether you want the coordinates to restart in every region or not (**Per-region coordinates** checkbox). Naturally, with per-region coordinates enabled, the individual regions will obey the coordinate settings of the level.

So `regn` should be updated as per below:

```
'regn'
    UINT8   enableRegions       (0=off, 1=on)
    UINT16  rowsPerRegion       (min=2, max=3333)
    UINT16  columnsPerRegion    (min=2, max=3333)
    UINT16  numRegions
    UINT8   perRegionCoords     (0=off, 1=on)
```

You can do it in your upcoming PR, or I'll do it later 😄

**Comment by johnnovak** [comment]
Fixed.
