### ISSUE TITLE
Platform: consider making `cmd` the modifier key on MacOS

### ISSUE THREAD

**Issue by peterb12** [johnnovak/gridmonger#16]
For most Mac programs, "cmd" is the primary modifier key, as opposed to control. If the framework you're using allows it, you might consider making that the equivalent of control on the platform.

Let's be honest, anyone using Gridmonger is gonna be fine using control instead. And changing documentation strings would be annoying. But I'll suggest it anyway in case you somehow get this "for free".

(By the way, in case no one else has said it to you - I *really* appreciate your making GridMonger multi-platform. I use it on both Mac and Windows.)

**Comment by johnnovak** [comment]
> For most Mac programs, "cmd" is the primary modifier key, as opposed to control. If the framework you're using allows it, you might consider making that the equivalent of control on the platform.

It's my own GUI framework, so it allows what I teach it to allow. 😎 It sits on top of GLFW for OpenGL context and OS-specific input/windowing system abstractions, so I'm interpreting the raw keyboard events myself.

> Let's be honest, anyone using Gridmonger is gonna be fine using control instead. And changing documentation strings would be annoying. But I'll suggest it anyway in case you somehow get this "for free".

It's a fair point and it tripped me up a few times as well on my Mac. It's not particularly hard to do, and another Mac user asked for it last week, so I'll just default to Cmd on Mac. Then you can switch it back to Ctrl in the preferences even on the Mac if you wish to do so.

> (By the way, in case no one else has said it to you - I _really_ appreciate your making GridMonger multi-platform. I use it on both Mac and Windows.)

Thanks, man 😎 Yeah, doing anything for a single platform only seems wasted effort to me, personally. I want to be able to keep using my own programs on any major OSes if I switchny main OS in the future. Plus although I use GM on Windows to play games, I develop it on my MacBook 99% of the time. Just a lot more convenient for me, personally, than to sit in front of my desktop PC.

I also find doing things cross-platform by default good for hardening and it improves your design. It's hard to retrofit it. Also, GM started 50% as a vehicle to test my custom-drawn GUI ideals to create a nice UX that looks and behaves the same way on all platforms, and a "catalyst" to develop my own GUI toolkit.

My views on cross-platform UIs if you're interested. I wrote it in 2016 but still 100% relevant.
https://blog.johnnovak.net/2016/05/29/cross-platform-gui-toolkit-trainwreck-2016-edition/

And yeah, an official Linux release is coming this year too at some point.

**Comment by johnnovak** [comment]
This has been implemented.
