### ISSUE TITLE
Enhancement: Set direction of numbering for numbered notes

### ISSUE THREAD

**Issue by peterb12** [johnnovak/gridmonger#17]
It took me a while to discover the numbered notes in Gridmonger but now they are probably my most-used type of note. There are different ways one could imagine doing numbering, but I think your solution of "Yeah look buddy we assign numbers automatically, deal with it" is actually pretty elegant and avoids the UI hassle of trying to individually manage number assignments; the other major concept would be "number them in the order in which they're encountered" but in practice **reading** a map that's numbered that way is annoying as hell.

_However_, there is one enhancement that might make perfect sense given Gridmonger's existing UI: if I'm exploring a dungeon where I'm starting in the lower right of the grid, then "things are numbered from the upper left" is precisely wrong. Gridmonger already has the concept of "numbers start from the northwest or southwest" in the level properties, so maybe a similar "numbers flow in this direction starting from this corner" would work.

As with most of my ERs, this is not a deal breaker, just something I think about when looking at my auto-numbered-numbers.

**Comment by johnnovak** [comment]
> It took me a while to discover the numbered notes in Gridmonger but now they are probably my most-used type of note. There are different ways one could imagine doing numbering, but I think your solution of "Yeah look buddy we assign numbers automatically, deal with it" is actually pretty elegant and avoids the UI hassle of trying to individually manage number assignments; the other major concept would be "number them in the order in which they're encountered" but in practice **reading** a map that's numbered that way is annoying as hell.

Not just elegant but also very practical. If you start deleting notes, you'd need to deal with holes in the numbering. Then if you start moving, deleting, cutting, pasting, etc. selections, all hell breaks lose. E.g., let's suppose you select half your map with half your numbered notes, move that over the _other_ half that contains the rest of the numbered notes, and maybe also move beyond the edges of the map so you "lose" some notes in the moved selection. Well, then what? 😎 

The auto-numbering takes care of all those weird edge cases automatically and it always does the right thing.

> _However_, there is one enhancement that might make perfect sense given Gridmonger's existing UI: if I'm exploring a dungeon where I'm starting in the lower right of the grid, then "things are numbered from the upper left" is precisely wrong. Gridmonger already has the concept of "numbers start from the northwest or southwest" in the level properties, so maybe a similar "numbers flow in this direction starting from this corner" would work.

Yeah, I could add a "Numbered notes origin" radio button below Origin in the map & level properties dialog. I could add "northwest or southwest", or maybe even all four corners, but I have my doubts about the usefulness of that extra flexibility feature.

My point: in reality, even if you enter the dungeon in one of the four corners, you're not usually exploring the map neatly row by row.  Exploration is almost always non-linear, or maybe follows a spiral-like pattern in some dungeons—then what? In real dungeons, you can pretty much start from any square, so the numbering won't neatly follow the order you explore the dungeon anyway. With a single fixed numbering order we have consistency—normal English reading order, end of story. And I'd argue consistency is more important when you "read" the map later on, and it does not really matter in what order you actually explored it.

So I'll need to mull over this a bit, but please try to convince me. I'm leading a bit towards a "no", currently.

**Comment by johnnovak** [comment]
Closing as I've decided not to implement this and no one is trying to convince me 😆
