### ISSUE TITLE
mistake in the manual - "Nudge Level" in Advanced Editing

### ISSUE THREAD

**Issue by jaadus** [johnnovak/gridmonger#18]
### Actual:
The Advanced Editing page in the manual says `Press Ctrl+E to enter Nudge Preview Mode`, which is the key combo for "Resize Level".

### Expected:
The actual key combo is `Ctrl+G`, as noted in the Keyboard Shortcuts page.

**Comment by johnnovak** [comment]
Thanks @jaadus, this will be fixed when the next version is out.
