### ISSUE TITLE
Enhancement Request: Grid Numbers

### ISSUE THREAD

**Issue by dericpage** [johnnovak/gridmonger#21]
A handy option would be a way to automatically place grid numbers.  Basically having an extra row and column to each contain one half of the grid's coordinate pairs showing on the map without needing to check the coordinates shown in the bottom right of the window.

Something like this:
```
   00 01 02 03 04 05 06 07 08 09
00
01
02
03
04
05
06
07
08
09
```

**Comment by dericpage** [comment]
Nevermind.  Just found it.

**Comment by johnnovak** [comment]
@dericpage Glad you've found it 😄 Reading the manual helps finding these little "hidden" features; there are many of them.
