### ISSUE TITLE
Window scaling on macOS

### ISSUE THREAD

**Issue by Koston-0xDEADBEEF** [johnnovak/gridmonger#22]
On macOS, using display resolution 1920x1080 on a screen with native resolution 3840x2160, macOS uses the native resolution for the video signal, but scales the UI x2. Gridmonger scaling range doesn't accommodate this setup very well; at 100% scaling a simple 26x26 grid map doesn't fully fit on screen vertically.

**Comment by johnnovak** [comment]
@Koston-0xDEADBEEF So then you adjust the scaling in the Gridmonger preferences, no? Doesn't that solve your issue?

**Comment by Koston-0xDEADBEEF** [comment]
100% scaling is the lowest allowed value, but it would need to be much lower (25-50%).

**Comment by johnnovak** [comment]
> 100% scaling is the lowest allowed value, but it would need to be much lower (25-50%).

Ok I can can easily do that. Can you post a screenshot of what you see on the screen, just to be sure I understand?

**Comment by Koston-0xDEADBEEF** [comment]
<img width="1125" alt="image" src="https://github.com/user-attachments/assets/c7dd6283-d602-423e-91be-be6ad38e14d1">

**Comment by johnnovak** [comment]
@Koston-0xDEADBEEF Hmm, okay, but have you tried changing the _map_ zoom level as well with the `-` key? I could allow sub-100% interface zoom levels, but the interface scaling looks fine here to me, I don't imagine anybody would want it smaller than that.

Can you try decreasing the map's zoom level and report back? Looks you're using the default zoom level here, so you can make the map appear a lot smaller by pressing the `-` key a few times.

**Comment by Koston-0xDEADBEEF** [comment]
I had not, that did the trick! Sorry for troubling you, apparently I didn't read the manual carefully enough.
