### ISSUE TITLE
Feature request: Export as image

### ISSUE THREAD

**Issue by Koston-0xDEADBEEF** [johnnovak/gridmonger#23]
Ability to export maps as PNG images via command-line using specified theme would be useful for sharing maps with consistent formatting. This isn't terribly important, but nice to have.

**Comment by johnnovak** [comment]
> Ability to export maps as PNG images via command-line using specified theme would be useful for sharing maps with consistent formatting. This isn't terribly important, but nice to have.

Yeah, it will come, it's just not so trivial (if I want to do it well and not just half-ass it 😆).

**Comment by Koston-0xDEADBEEF** [comment]
Alright, thanks! Gridmonger seems really well designed and implemented.

**Comment by johnnovak** [comment]
> Alright, thanks! Gridmonger seems really well designed and implemented.

Thanks man 😎
