### ISSUE TITLE
Document persistence format?  Support for other save formats?

### ISSUE THREAD

**Issue by fmoo** [johnnovak/gridmonger#5]
Love the tool and was thinking of using it as a design tool for other games.

Have you documented the persistence format anywhere to make it easier to import?  Any plans to add json as an output format?  

I can work from https://github.com/johnnovak/gridmonger/blob/master/src/persistence.nim#L1116 to port but I'm not super familiar with nim.

**Comment by johnnovak** [comment]
Glad you like the program!

Please see the relevant section of the manual regarding the file format:
https://gridmonger.johnnovak.net/manual/appendixes/advanced-usage.html#map-file-format

I'm not planning to add JSON export support.
