### ISSUE TITLE
Trying out the link feaature shift-G "Cannot link current cell"

### ISSUE THREAD

**Issue by j-rodman** [johnnovak/gridmonger#7]
No idea what I'm doing wrong.  I think i'm in the standard mode.  I hit shift-G and just  "cannot link current cell" in the status bar.   No idea why. Googling for error string returns nothing.

I'm on win 64, using the portable install.  Version 1.1.0 (6e74ced)

**Comment by johnnovak** [comment]
Have you read the manual? I need more info to help you. It would be best to upload the problematic map file and describe the exact steps you are doing so I can reproduce.

**Comment by j-rodman** [comment]
I have read the manual.  The the manual says you press Shift-G to enter link mode.  It doesn't enter link mode.  It gives me that error.  I'm left without any idea what it wants.  But it's crashed on me a few times now so my energy to pursue this has closed.
